apiVersion: v1
kind: Service
metadata:
  name: rest-demo-loadbalancer
  labels:
    app: rest-demo
spec:
  type: LoadBalancer
  selector:
    app: rest-demo
  ports:
    - port: 8080
      targetPort: 8080